/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Pc
 */
import javax.swing.Timer;
import java.awt.Color;

public class semaforo1 extends javax.swing.JFrame {
    
    int luz = 0;
    Timer timer;
    int tiempoRestante;
    Timer timerCambio;
    Timer timerContador;
    
    
    final int DURACION_ROJO = 10;
    final int DURACION_AMARILLO = 5;
    final int DURACION_VERDE = 8;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(semaforo1.class.getName());

    /**
     * Creates new form semaforo1
     */
    public semaforo1() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        rojo.setBackground(Color.GRAY);
        amarillo.setBackground(Color.GRAY);
        verde.setBackground(Color.GRAY);
        
    tiemporojo.setText("0");
    tiempoamarillo.setText("0");
    tiempoverde.setText("0");
        
        iniciar.addActionListener(e -> {
        iniciar.setEnabled(true);
        cambiarLuz();
        });
        
    }
     
    private void cambiarLuz (){
    
    rojo.setBackground(Color.GRAY);
    amarillo.setBackground(Color.GRAY);
    verde.setBackground(Color.GRAY);
    
    tiemporojo.setText("0");
    tiempoamarillo.setText("0");
    tiempoverde.setText("0");
    
    if (timerCambio !=null) timerCambio.stop();
    if (timerContador !=null) timerContador.stop();
        
    switch (luz){
        case 0 -> {
        verde.setBackground(Color.GREEN);
        tiempoRestante = DURACION_VERDE;
        tiempoverde.setText(String.valueOf(tiempoRestante));
        }
        
        case 1 -> {
        amarillo.setBackground(Color.YELLOW);
        tiempoRestante = DURACION_AMARILLO;
        tiempoamarillo.setText(String.valueOf(tiempoRestante));
        }
        
        case 2 -> {
        rojo.setBackground(Color.RED);
        tiempoRestante = DURACION_ROJO;
        tiemporojo.setText(String.valueOf(tiempoRestante));
        }
    }
    
    timerCambio = new Timer(tiempoRestante * 1000, e ->{
    luz = (luz + 1)%3;
    cambiarLuz();
    });
    
    timerCambio.setRepeats(false);
    timerCambio.start();
    
    timerContador = new Timer (1000, e ->{
        tiempoRestante--;
        if (tiempoRestante >= 0){
        switch (luz){
            case 0 -> tiempoverde.setText(String.valueOf(tiempoRestante));
            case 1 -> tiempoamarillo.setText(String.valueOf(tiempoRestante));
            case 2 -> tiemporojo.setText(String.valueOf(tiempoRestante));
        }
       }      
    });
    timerContador.start();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        continuar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        verde = new javax.swing.JLabel();
        amarillo = new javax.swing.JLabel();
        rojo = new javax.swing.JLabel();
        tiempoverde = new javax.swing.JLabel();
        tiempoamarillo = new javax.swing.JLabel();
        tiemporojo = new javax.swing.JLabel();
        iniciar = new javax.swing.JButton();
        detener = new javax.swing.JButton();
        Continuar = new javax.swing.JButton();
        regresar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        continuar.setText("Continuar");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        verde.setBackground(new java.awt.Color(102, 255, 102));
        verde.setOpaque(true);

        amarillo.setBackground(new java.awt.Color(255, 255, 0));
        amarillo.setOpaque(true);

        rojo.setBackground(new java.awt.Color(255, 0, 0));
        rojo.setOpaque(true);

        tiempoverde.setForeground(new java.awt.Color(51, 255, 0));
        tiempoverde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tiempoverde.setText("--");

        tiempoamarillo.setForeground(new java.awt.Color(255, 255, 51));
        tiempoamarillo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tiempoamarillo.setText("--");

        tiemporojo.setForeground(new java.awt.Color(255, 0, 0));
        tiemporojo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tiemporojo.setText("--");

        iniciar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        iniciar.setText("Iniciar");
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });

        detener.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        detener.setText("Detener");
        detener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detenerActionPerformed(evt);
            }
        });

        Continuar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        Continuar.setText("Continuar");
        Continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinuarActionPerformed(evt);
            }
        });

        regresar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(amarillo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tiempoamarillo))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(verde, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tiempoverde))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rojo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tiemporojo))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Continuar)
                            .addComponent(iniciar))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(detener)
                            .addComponent(regresar))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(tiempoverde))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(verde, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(tiempoamarillo)
                        .addGap(51, 51, 51)
                        .addComponent(tiemporojo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(amarillo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(rojo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iniciar)
                    .addComponent(detener))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Continuar)
                    .addComponent(regresar))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void detenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detenerActionPerformed
        // TODO add your handling code here:
    if (timerCambio != null) timerCambio.stop();
    if (timerCambio != null) timerContador.stop();
    
    detener.setEnabled (false);
    iniciar.setEnabled (true);
    continuar.setEnabled (true);
    }//GEN-LAST:event_detenerActionPerformed

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        // TODO add your handling code here:
        iniciar.setEnabled (false);
        detener.setEnabled (true);
        continuar.setEnabled (false);
        luz = 0;
        cambiarLuz();
    }//GEN-LAST:event_iniciarActionPerformed

    private void ContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinuarActionPerformed
        // TODO add your handling code here:
        if (tiempoRestante > 0){
        timerCambio = new Timer (tiempoRestante * 1000, e -> {
        luz = (luz + 1)%3;
        });
        timerCambio.setRepeats(false);
        timerCambio.start();
        
        timerContador = new Timer (1000, e -> {
        tiempoRestante--;
        if (tiempoRestante >= 0){
        switch (luz){
            case 0 -> tiempoverde.setText(String.valueOf(tiempoRestante));
            case 1 -> tiempoamarillo.setText(String.valueOf(tiempoRestante));
            case 2 -> tiemporojo.setText(String.valueOf(tiempoRestante));
        }
        }
        });
        timerContador.start();
        
        continuar.setEnabled(false);
        detener.setEnabled(true);
        iniciar.setEnabled(false);
        }
    }//GEN-LAST:event_ContinuarActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
        loggin1 newframe=new loggin1();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new semaforo1().setVisible(true));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Continuar;
    private javax.swing.JLabel amarillo;
    private javax.swing.JButton continuar;
    private javax.swing.JButton detener;
    private javax.swing.JButton iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton regresar;
    private javax.swing.JLabel rojo;
    private javax.swing.JLabel tiempoamarillo;
    private javax.swing.JLabel tiemporojo;
    private javax.swing.JLabel tiempoverde;
    private javax.swing.JLabel verde;
    // End of variables declaration//GEN-END:variables

}